CREATE TABLE tutor(
id_tutor integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR(100),
data_nascimento DATE,
CPF VARCHAR(15),
email VARCHAR(80),
telefone VARCHAR(15)
 
 
);
 
INSERT INTO tutor(id_tutor,nome,data_nascimento,CPF,email,telefone)
VALUES (1,'Lucas Almeida Rocha','1992-03-14','000.000.000-01','lucas.rocha@example.com','(14) 90000-0001');
 
INSERT INTO tutor(id_tutor,nome,data_nascimento,CPF,email,telefone)
VALUES (2,'Mariana Costa Ferreira','1988-07-27','000.000.000-02','mariana.ferreira@example.com','(14) 90000-0002');
 
INSERT INTO tutor(id_tutor,nome,data_nascimento,CPF,email,telefone)
VALUES (3,'Rafael Martins Souza','1995-11-05','000.000.000-03','rafael.souza@example.com','(14) 90000-0003');
 
INSERT INTO tutor(id_tutor,nome,data_nascimento,CPF,email,telefone)
VALUES (4,'Camila Oliveira Santos','1990-01-19','000.000.000-04','camila.santos@example.com','(14) 90000-0004');
 
INSERT INTO tutor(id_tutor,nome,data_nascimento,CPF,email,telefone)
VALUES (5,'Pedro Henrique Lima','1985-05-31','000.000.000-05','pedro.lima@example.com','(14) 90000-0005');
 
INSERT INTO tutor(id_tutor,nome,data_nascimento,CPF,email,telefone)
VALUES (6,'Juliana Mendes Carvalho','1990-01-19','000.000.000-06','juliana.carvalho@example.com','(14) 90000-0006');
 
INSERT INTO tutor(id_tutor,nome,data_nascimento,CPF,email,telefone)
VALUES (7,'André Luiz Barbosa','1993-12-22','000.000.000-07','andre.barbosa@example.com','(14) 90000-0007');
 
INSERT INTO tutor(id_tutor,nome,data_nascimento,CPF,email,telefone)
VALUES (8,'Fernanda Ribeiro Alves','1987-04-16','000.000.000-08','fernanda.alves@example.com','(14) 90000-0008');
 
INSERT INTO tutor(id_tutor,nome,data_nascimento,CPF,email,telefone)
VALUES (9,'Gustavo Pereira Dias','1996-08-03','000.000.000-09','gustavo.dias@example.com','(14) 90000-0009');
 
INSERT INTO tutor(id_tutor,nome,data_nascimento,CPF,email,telefone)
VALUES (10,'Beatriz Nunes Moreira','1991-10-21','000.000.000-10','beatriz.moreira@example.com','(14) 90000-0010');
 
 
 
 
CREATE TABLE paciente(
id_paciente integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
id_tutor integer,
nome VARCHAR(100),
raca VARCHAR(50),
data_nascimento DATE,
peso NUMERIC(3,2),
problema VARCHAR(250),
 
CONSTRAINT fk_tutor FOREIGN KEY (ID_tutor)
REFERENCES tutor(ID_tutor)
 
 
);
INSERT INTO paciente (id_tutor, nome, raca, DATA_NASCIMENTO, PESO, PROBLEMA)
values(10, 'lulu', 'cachorrin', '2026-05-12', 0.1, 'Dor de ouvido');
 
 
INSERT INTO paciente ( id_tutor, nome, raca, DATA_NASCIMENTO, PESO, PROBLEMA)
values( 1, 'Diuly', 'Cocker', '2012-12-02', 10, 'Preguiça');
 

INSERT INTO paciente (id_tutor, nome, raca, DATA_NASCIMENTO, PESO, PROBLEMA)
values(2, 'Thor', 'Golden Retriever', '2020-04-12', 31.5, 'Dermatite');
 

INSERT INTO paciente (id_tutor, nome, raca, DATA_NASCIMENTO, PESO, PROBLEMA)
values(3, 'gigi', 'labrador', '2020-08-13', 23.2, 'diarreia');
 

INSERT INTO paciente (id_tutor, nome, raca, DATA_NASCIMENTO, PESO, PROBLEMA)
values(4, 'nina', 'Poodle', '2022-11-11', 4.7, 'Otite');
 

INSERT INTO paciente (id_tutor, nome, raca, DATA_NASCIMENTO, PESO, PROBLEMA)
values(5, 'lola', 'Yorkshire Terrier', '2026-01-20', 6.3, 'Gastrite');
 

INSERT INTO paciente (id_tutor, nome, raca, DATA_NASCIMENTO, PESO, PROBLEMA)
values(6, 'Simba', 'SRD', '2018-06-30', 6.3, 'Problema dentário');
 

INSERT INTO paciente (id_tutor, nome, raca, DATA_NASCIMENTO, PESO, PROBLEMA)
values(7, 'Max', 'Pastor Alemão', '2021-05-09', 30.8, 'Artrite');
 

INSERT INTO paciente (id_tutor, nome, raca, DATA_NASCIMENTO, PESO, PROBLEMA)
values(8, 'Bob', 'Bulldog Francês', '2023-10-28', 13.1, 'Problema respiratório');
 

INSERT INTO paciente (id_tutor, nome, raca, DATA_NASCIMENTO, PESO, PROBLEMA)
values(9, 'Frida', 'Dachshund', '2025-03-17', 6.1, 'Dor na coluna');
 
 
SELECT * FROM  paciente;
 
 
SELECT p.id_paciente
	,p.nome
	,(SELECT t.nome FROM TUTOR t
	WHERE t.id_tutor = p.id_tutor) AS nome_tutor
FROM paciente p
WHERE p.id_tutor = (SELECT tu.id_tutor FROM tutor tu
					WHERE tu.nome LIKE 'Maria%'
					AND tu.id_tutor = p.id_paciente);
					
					
 
CREATE TABLE veterinario(
id_veterinario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR(100),
especialidade VARCHAR(100),
CPF VARCHAR(15),
email VARCHAR(80),
telefone VARCHAR(15)
 
);
 
INSERT INTO veterinario(id_veterinario,nome,especialidade,CPF,email,telefone)
VALUES (1,'Carlos Eduardo Martins','Clínica Geral','100.230.000-01','carlos.martins@example.com','(18) 90000-1001');
 
INSERT INTO veterinario(id_veterinario,nome,especialidade,CPF,email,telefone)
VALUES (2,'Ana Paula Ribeiro','Dermatologia Veterinária','000.056.034-02','ana.ribeiro@example.com','(18) 90000-1002');
 
INSERT INTO veterinario(id_veterinario,nome,especialidade,CPF,email,telefone)
VALUES (3,'Marcelo Henrique Souza','Ortopedia','000.200.030-03','marcelo.souza@example.com','(18) 90000-1003');
 
 
INSERT INTO veterinario(id_veterinario,nome,especialidade,CPF,email,telefone)
VALUES (4,'Juliana Costa Almeida','Cardiologia Veterinária','000.500.030-03','juliana.almeida@example.com','(18) 90000-1004');
 
INSERT INTO veterinario(id_veterinario,nome,especialidade,CPF,email,telefone)
VALUES (5,'Roberto Lima Ferreira','Cirurgia Veterinária','008.700.030-03','roberto.ferreira@example.com','(18) 90000-1005');
 
INSERT INTO veterinario(id_veterinario,nome,especialidade,CPF,email,telefone)
VALUES (6,'Fernanda Oliveira Santos','Oftalmologia Veterinária','008.980.030-03','fernanda.santos@example.com','(18) 90000-1006');
 
INSERT INTO veterinario(id_veterinario,nome,especialidade,CPF,email,telefone)
VALUES (7,'Gustavo Mendes Rocha','Oncologia Veterinária','008.480.030-03','gustavo.rocha@example.com','(18) 90000-1007');
 
INSERT INTO veterinario(id_veterinario,nome,especialidade,CPF,email,telefone)
VALUES (8,'Camila Nunes Barbosa','Neurologia Veterinária','008.480.039-03','camila.barbosa@example.com','(18) 90000-1008');
 
INSERT INTO veterinario(id_veterinario,nome,especialidade,CPF,email,telefone)
VALUES (9,'Ricardo Alves Pereira','Anestesiologia','008.480.567-03','ricardo.pereira@example.com','(18) 90000-1009');
 
INSERT INTO veterinario(id_veterinario,nome,especialidade,CPF,email,telefone)
VALUES (10,'Beatriz Fernandes Costa','Medicina Felina','987.480.567-03','beatriz.costa@example.com','(18) 90000-1010');
 
 
 
 
SELECT * FROM VETERINARIO;
 
CREATE TABLE agendamento(
id_agendamento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
id_paciente integer,
id_veterinario integer,
dia DATE,
horario TIME,
codigo integer,
 
 
CONSTRAINT fk_paciente FOREIGN KEY (ID_paciente)
REFERENCES paciente(ID_paciente),
 
CONSTRAINT fk_veterinario FOREIGN KEY (ID_veterinario)
REFERENCES veterinario(ID_veterinario)
 
);
 
INSERT INTO AGENDAMENTO (id_paciente,id_veterinario,dia, horario,codigo)
VALUES (1,1,'2025-12-09','08:30:00',9);
 
UPDATE AGENDAMENTO SET MOTIVO = 'Exame de Sangue'
WHERE codigo = 9 ;
 
 
INSERT INTO AGENDAMENTO (id_paciente,id_veterinario,dia, horario,codigo)
VALUES (2,2,'2025-02-28','11:54:00',10);

UPDATE AGENDAMENTO SET MOTIVO = 'Dor na Pata'
WHERE codigo = 10;

 
 
INSERT INTO AGENDAMENTO (id_paciente,id_veterinario,dia, horario,codigo)
VALUES (3,3,'2025-12-09','09:12:34',2);
 
UPDATE AGENDAMENTO SET MOTIVO = 'Sangramento'
WHERE codigo = 2 ;
 
INSERT INTO AGENDAMENTO (id_paciente,id_veterinario,dia, horario,codigo)
VALUES (4,4,'2026-10-15','14:30:00',5);

UPDATE AGENDAMENTO SET MOTIVO = 'Exame de Sangue'
WHERE codigo = 5 ;

 
INSERT INTO AGENDAMENTO (id_paciente,id_veterinario,dia, horario,codigo)
VALUES (5,5,'2026-12-03','11:23:24',4);
 
UPDATE AGENDAMENTO SET MOTIVO = 'Dor de Cabeça'
WHERE codigo = 4 ;
 
INSERT INTO AGENDAMENTO (id_paciente,id_veterinario,dia, horario,codigo)
VALUES (6,6,'2025-04-10','07:30:00',7);
 
UPDATE AGENDAMENTO SET MOTIVO = 'Exame de rotina'
WHERE codigo = 7;
 
INSERT INTO AGENDAMENTO (id_paciente,id_veterinario,dia, horario,codigo)
VALUES (7,7,'2026-09-25','08:35:00',1);
 
UPDATE AGENDAMENTO SET MOTIVO = 'Dor de ouvido'
WHERE codigo = 1 ;
 
INSERT INTO AGENDAMENTO (id_paciente,id_veterinario,dia, horario,codigo)
VALUES (8,8,'2025-06-09','17:30:00',8);
 
UPDATE AGENDAMENTO SET MOTIVO = 'Surdez'
WHERE codigo = 8 ;
 
INSERT INTO AGENDAMENTO (id_paciente,id_veterinario,dia, horario,codigo)
VALUES (9,9,'2025-02-26','20:40:00',6);

UPDATE AGENDAMENTO SET MOTIVO = 'Exame de Sangue'
WHERE codigo = 6 ;
 
 
INSERT INTO AGENDAMENTO (id_paciente,id_veterinario,dia, horario,codigo)
VALUES (10,10,'2025-05-09','15:30:00',3);

UPDATE AGENDAMENTO SET MOTIVO = 'preguiça'
WHERE codigo = 3 ;
 
ALTER TABLE AGENDAMENTO ADD motivo VARCHAR(100);

 
CREATE TABLE medicamento(
id_MEDICAMENTO integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nome VARCHAR(100),
dta_fabricacao DATE,
vencimento DATE,
lote VARCHAR(10),
estoque INTEGER
);
 
INSERT INTO medicamento(nome,dta_fabricacao,vencimento,lote,estoque)
VALUES ('Amoxicilina 500mg', '2025-01-15', '2027-01-15', 'LOTAMX001', 50);

UPDATE MEDICAMENTO SET DESCRICAO = 'iNFECÇÕES'
WHERE NOME = 'Amoxicilina 500mg';

UPDATE MEDICAMENTO SET PRECO = 50.00
WHERE NOME = 'Amoxicilina 500mg';
 
INSERT INTO MEDICAMENTO (nome, dta_fabricacao, vencimento, lote, estoque)
VALUES ('Dipirona 500mg', '2025-02-10', '2027-02-10', 'LOTDIP002', 80);
 
UPDATE MEDICAMENTO SET PRECO = 30.00
WHERE NOME = 'Dipirona 500mg';

UPDATE MEDICAMENTO SET descricao = 'Dores'
WHERE NOME = 'Dipirona 500mg';

INSERT INTO MEDICAMENTO (nome, dta_fabricacao, vencimento, lote, estoque)
VALUES ('Prednisolona 20mg', '2025-03-05', '2027-03-05', 'LOTPRE003', 35);

UPDATE MEDICAMENTO SET PRECO = 48.00
WHERE NOME = 'Prednisolona 20mg'; 

INSERT INTO MEDICAMENTO (nome, dta_fabricacao, vencimento, lote, estoque)
VALUES ('Carprofeno 50mg', '2025-01-20', '2026-12-20', 'LOTCAR004', 40);

UPDATE MEDICAMENTO SET PRECO = 70.00
WHERE NOME = 'Carprofeno 50mg'; 

UPDATE MEDICAMENTO SET descricao = 'Anti-inflamatorio'
WHERE NOME = 'Carprofeno 50mg'; 

INSERT INTO MEDICAMENTO (nome, dta_fabricacao, vencimento, lote, estoque)
VALUES ('Omeprazol 20mg', '2025-04-12', '2027-04-12', 'LOTOME005', 60);

UPDATE MEDICAMENTO SET PRECO = 15.00
WHERE NOME = 'Omeprazol 20mg';

INSERT INTO MEDICAMENTO (nome, dta_fabricacao, vencimento, lote, estoque)
VALUES ('Cefalexina 500mg', '2025-05-08', '2027-05-08', 'LOTCEF006', 45);

UPDATE MEDICAMENTO SET PRECO = 67.00
WHERE NOME = 'Cefalexina 500mg';

INSERT INTO MEDICAMENTO (nome, dta_fabricacao, vencimento, lote, estoque)
VALUES ('Meloxicam 0,5mg', '2025-06-18', '2027-06-18', 'LOTMEL007', 30);

UPDATE MEDICAMENTO SET PRECO = 100.00
WHERE NOME = 'Meloxicam 0,5mg';

UPDATE MEDICAMENTO SET descricao = 'Inchaço'
WHERE NOME = 'Carprofeno 50mg'; 

INSERT INTO MEDICAMENTO (nome, dta_fabricacao, vencimento, lote, estoque)
VALUES ('Enrofloxacino 150mg', '2025-02-25', '2027-02-25', 'LOTENR008', 25);

UPDATE MEDICAMENTO SET PRECO = 130.00
WHERE NOME = 'Enrofloxacino 150mg';

INSERT INTO MEDICAMENTO (nome, dta_fabricacao, vencimento, lote, estoque)
VALUES ('Ivermectina 6mg', '2025-07-10', '2027-07-10', 'LOTIVE009', 70);

UPDATE MEDICAMENTO SET PRECO = 85.00
WHERE NOME = 'Ivermectina 6mg';

INSERT INTO MEDICAMENTO (nome, dta_fabricacao, vencimento, lote, estoque)
VALUES ('Suplemento Vitamínico', '2025-08-01', '2027-08-01', 'LOTSUP010', 100);

UPDATE MEDICAMENTO SET PRECO = 35.00
WHERE NOME = 'Suplemento Vitamínico';

INSERT INTO MEDICAMENTO (nome, dta_fabricacao, vencimento, lote, estoque)
VALUES ('Antibiótico Veterinário', '2025-12-01', '2027-12-01', 'LOTANT020', 55);

UPDATE MEDICAMENTO SET PRECO = 105.00
WHERE NOME = 'Antibiótico Veterinário';

UPDATE MEDICAMENTO SET descricao = 'Infecções'
WHERE NOME = 'Antibiótico Veterinário';

INSERT INTO MEDICAMENTO (nome, dta_fabricacao, vencimento, lote, estoque)
VALUES ('Ivermectina 6mg', '2025-11-15', '2027-11-15', 'LOTIVE019', 70);

UPDATE MEDICAMENTO SET PRECO = 25.00
WHERE NOME = 'Ivermectina 6mg';

ALTER TABLE MEDICAMENTO ADD preco NUMERIC(3,2);
ALTER TABLE MEDICAMENTO ADD descricao VARCHAR(150);

 
CREATE TABLE item_receita(
id_item_receita integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
id_medicamento integer,
quantidade integer,
horario TIME,
frequencia DATE,
dosagem NUMERIC(2,1),
 
 
 
CONSTRAINT fk_medicamento FOREIGN KEY (ID_medicamento)
REFERENCES medicamento(ID_medicamento)
);
 
INSERT INTO ITEM_RECEITA (id_medicamento, quantidade, horario, frequencia, dosagem,id_receita)
VALUES (1, 10, '08:00:00', '2025-05-09', 1.0,1);
 
INSERT INTO ITEM_RECEITA (id_medicamento, quantidade, horario, frequencia, dosagem)
VALUES (2, 20, '12:00:00', '2025-05-10', 0.5);
UPDATE ITEM_RECEITA SET ID_RECEITA = 4
WHERE ID_ITEM_RECEITA = 2;

 
INSERT INTO ITEM_RECEITA (id_medicamento, quantidade, horario, frequencia, dosagem)
VALUES (3, 15, '18:00:00', '2025-05-11', 2.0);
UPDATE ITEM_RECEITA SET ID_RECEITA = 5
WHERE ID_ITEM_RECEITA = 3;
 
INSERT INTO ITEM_RECEITA (id_medicamento, quantidade, horario, frequencia, dosagem)
VALUES (4, 10, '08:30:00', '2025-05-12', 1.5);
UPDATE ITEM_RECEITA SET ID_RECEITA = 6
WHERE ID_ITEM_RECEITA = 4;
 
INSERT INTO ITEM_RECEITA (id_medicamento, quantidade, horario, frequencia, dosagem)
VALUES (5, 30, '07:00:00', '2025-05-13', 1.0);
UPDATE ITEM_RECEITA SET ID_RECEITA = 7
WHERE ID_ITEM_RECEITA = 5;
 
INSERT INTO ITEM_RECEITA (id_medicamento, quantidade, horario, frequencia, dosagem)
VALUES (6, 14, '20:00:00', '2025-05-14', 0.5);
UPDATE ITEM_RECEITA SET ID_RECEITA = 8
WHERE ID_ITEM_RECEITA = 6;
 
INSERT INTO ITEM_RECEITA (id_medicamento, quantidade, horario, frequencia, dosagem)
VALUES (7, 21, '09:00:00', '2025-05-15', 1.0);
UPDATE ITEM_RECEITA SET ID_RECEITA = 8
WHERE ID_ITEM_RECEITA = 7;
 
INSERT INTO ITEM_RECEITA (id_medicamento, quantidade, horario, frequencia, dosagem)
VALUES (8, 10, '14:00:00', '2025-05-16', 2.0);
UPDATE ITEM_RECEITA SET ID_RECEITA = 9
WHERE ID_ITEM_RECEITA = 8;

INSERT INTO ITEM_RECEITA (id_medicamento, quantidade, horario, frequencia, dosagem)
VALUES (9, 12, '10:00:00', '2025-05-17', 1.5);
UPDATE ITEM_RECEITA SET ID_RECEITA = 10
WHERE ID_ITEM_RECEITA = 9;
 
INSERT INTO ITEM_RECEITA (id_medicamento, quantidade, horario, frequencia, dosagem)
VALUES (10, 30, '19:00:00', '2025-05-18', 0.5);
UPDATE ITEM_RECEITA SET ID_RECEITA = 11
WHERE ID_ITEM_RECEITA = 10;

INSERT INTO ITEM_RECEITA (id_medicamento, quantidade, horario, frequencia, dosagem,id_receita)
VALUES (11, 20, '12:00:00', '2025-05-10', 0.5,4);

INSERT INTO ITEM_RECEITA (id_medicamento, quantidade, horario, frequencia, dosagem,ID_RECEITA)
VALUES (12, 10, '08:30:00', '2025-05-12', 1.5,4);

INSERT INTO ITEM_RECEITA (id_medicamento, quantidade, horario, frequencia, dosagem,ID_RECEITA)
VALUES (1, 30, '07:00:00', '2025-05-13', 1.0,5);

INSERT INTO ITEM_RECEITA (id_medicamento, quantidade, horario, frequencia, dosagem,ID_RECEITA)
VALUES (2, 14, '20:00:00', '2025-05-14', 0.5,6);

INSERT INTO ITEM_RECEITA (id_medicamento, quantidade, horario, frequencia, dosagem,ID_RECEITA)
VALUES (3, 21, '09:00:00', '2025-05-15', 1.0,7);

INSERT INTO ITEM_RECEITA (id_medicamento, quantidade, horario, frequencia, dosagem,ID_RECEITA)
VALUES (4, 10, '14:00:00', '2025-05-16', 2.0,8);

INSERT INTO ITEM_RECEITA (id_medicamento, quantidade, horario, frequencia, dosagem,ID_RECEITA)
VALUES (5, 12, '10:00:00', '2025-05-17', 1.5,9);

INSERT INTO ITEM_RECEITA (id_medicamento, quantidade, horario, frequencia, dosagem,ID_RECEITA)
VALUES (6, 30, '19:00:00', '2025-05-18', 0.5,10);

INSERT INTO ITEM_RECEITA (id_medicamento, quantidade, horario, frequencia, dosagem,ID_RECEITA)
VALUES (6, 10, '08:00:00', '2025-05-19', 1.0,NULL);

CREATE TABLE receita(
id_receita integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
id_item_receita integer,
id_agendamento integer,
data_emissao DATE,
observacoes VARCHAR(150),
 
 
 
CONSTRAINT fk_item_receita FOREIGN KEY (ID_item_receita)
REFERENCES item_receita(ID_item_receita),
 
CONSTRAINT fk_agendamento FOREIGN KEY (ID_agendamento)
REFERENCES agendamento(ID_agendamento)
);

 
INSERT INTO receita (id_item_receita, id_agendamento, data_emissao, observacoes)
VALUES (2, 1, '2025-05-09', 'Administrar conforme orientação veterinária.');

INSERT INTO receita (id_item_receita, id_agendamento, data_emissao, observacoes)
VALUES (3, 2, '2025-05-10', 'Administrar após as refeições.');


INSERT INTO receita (id_item_receita, id_agendamento, data_emissao, observacoes)
VALUES (4, 3, '2025-05-11', 'Manter o tratamento durante 7 dias.');



INSERT INTO receita (id_item_receita, id_agendamento, data_emissao, observacoes)
VALUES (5, 4, '2025-05-12', 'Não interromper o tratamento sem orientação.');



INSERT INTO receita (id_item_receita, id_agendamento, data_emissao, observacoes)
VALUES (6, 5, '2025-05-13', 'Administrar nos horários indicados.');


INSERT INTO receita (id_item_receita, id_agendamento, data_emissao, observacoes)
VALUES (7, 6, '2025-05-14', 'Manter o medicamento fora do alcance dos animais.');


INSERT INTO receita (id_item_receita, id_agendamento, data_emissao, observacoes)
VALUES (8, 7, '2025-05-15', 'Retornar para avaliação após o tratamento.');


INSERT INTO receita (id_item_receita, id_agendamento, data_emissao, observacoes)
VALUES (9, 8, '2025-05-16', 'Administrar com água em quantidade adequada.');

INSERT INTO receita (id_item_receita, id_agendamento, data_emissao, observacoes)
VALUES (10, 9, '2025-05-17', 'Observar possíveis reações durante o tratamento.');


INSERT INTO receita (id_item_receita, id_agendamento, data_emissao, observacoes)
VALUES (10, 10, '2025-05-18', 'Seguir a prescrição veterinária.');

 
ALTER TABLE ITEM_RECEITA  ADD id_receita integer;
 
 
ALTER TABLE ITEM_RECEITA ADD CONSTRAINT fk_receita FOREIGN KEY (id_receita)
REFERENCES receita(id_receita);




 
/*ATIVIDADE1*/
SELECT * FROM VETERINARIO
WHERE especialidade like 'Dermatologia%'
 
/*ATIVIDADE2*/
SELECT p.ID_paciente
		,p.data_nascimento
		,EXTRACT (YEAR FROM CURRENT_date) - EXTRACT(YEAR FROM p.data_nascimento)
		FROM paciente p
WHERE EXTRACT (YEAR FROM CURRENT_date) - EXTRACT(YEAR FROM data_nascimento ) BETWEEN 2 AND 5
	
/* ATIVIDADE3*/
SELECT * FROM AGENDAMENTO
WHERE dia BETWEEN '2025-01-01' AND '2024-03-31';

/* ATIVIDADE4*/
SELECT * FROM medicamento
WHERE preco > 25

/* ATIVIDADE5*/
SELECT p.id_paciente
	,p.nome
	,(SELECT t.nome FROM TUTOR t
	WHERE t.id_tutor = p.id_tutor) AS nome_tutor
FROM paciente p
WHERE p.id_tutor = (SELECT tu.id_tutor FROM tutor tu
					WHERE tu.nome LIKE 'Pedro%'
					AND tu.id_tutor = p.id_tutor);

/* ATIVIDADE6*/
SELECT r.id_receita,
       r.data_emissao,
       r.id_agendamento
FROM receita r
WHERE r.data_emissao > '2024-06-01'
AND r.id_agendamento = (
    SELECT a.id_agendamento
    FROM AGENDAMENTO a
    WHERE a.id_veterinario = (
        SELECT v.id_veterinario
        FROM VETERINARIO v
        WHERE v.nome LIKE 'Camila Nunes%'
    )
);			

/* ATIVIDADE7*/	
SELECT p.id_item_receita
	,p.id_medicamento
	,(SELECT t.id_medicamento FROM medicamento t
	WHERE t.id_medicamento = p.id_medicamento) AS nome_medicamento
FROM ITEM_RECEITA p
WHERE p.id_medicamento = (SELECT tu.id_medicamento FROM medicamento tu
					WHERE nome LIKE 'Amoxicilina%'
					AND tu.id_medicamento = p.ID_MEDICAMENTO );


/* ATIVIDADE8*/	


/* ATIVIDADE9*/
SELECT p.id_agendamento
	,p.id_veterinario
	,p.motivo
	,(SELECT t.nome FROM veterinario t
	WHERE t.id_veterinario = p.id_veterinario) AS nome_veterinario
FROM AGENDAMENTO p
WHERE p.ID_VETERINARIO = (SELECT tu.id_veterinario FROM veterinario tu
					WHERE tu.nome LIKE 'Carlos%'
					AND tu.id_veterinario = p.ID_veterinario )
AND p.motivo = 'Exame de Sangue';


/* ATIVIDADE10*/
SELECT * FROM MEDICAMENTO 
WHERE descricao IS NOT NULL
AND preco > 50;



/* ATIVIDADE11*/
SELECT * FROM paciente
WHERE peso BETWEEN 3 AND 10;


/* ATIVIDADE12*/
SELECT p.ID_PACIENTE
	,p.id_tutor
	,p.peso
	,(SELECT t.nome FROM tutor t
	WHERE t.id_tutor = p.id_tutor) AS nome_tutor
FROM paciente p
WHERE p.ID_tutor = (SELECT tu.id_tutor FROM tutor tu
					WHERE tu.nome LIKE 'Rafael%'
					AND tu.id_tutor = p.ID_tutor )
AND p.peso > 5;

/* ATIVIDADE13*/
SELECT * FROM PACIENTE 
WHERE raca = 'cachorrin'
AND peso < 7;


/* ATIVIDADE14*/
SELECT r.id_agendamento,
		r.dia,
       r.id_paciente
	,(SELECT a.nome
    FROM paciente a
    WHERE a.id_paciente = r.id_paciente) AS nome_paciente,
    ( SELECT a.peso FROM paciente a 
    WHERE a.id_paciente = r.id_paciente) AS nome_peso

FROM AGENDAMENTO r
WHERE r.dia BETWEEN '2025-04-01' AND '2026-06-30';


/* ATIVIDADE15*/
SELECT * FROM PACIENTE
WHERE ID_PACIENTE NOT IN (
    SELECT ID_PACIENTE
    FROM AGENDAMENTO
);

/* ATIVIDADE16*/
SELECT *FROM PACIENTE
WHERE ID_PACIENTE NOT IN (
    SELECT ID_PACIENTE
    FROM AGENDAMENTO
    WHERE dia BETWEEN '2024-01-01' AND '2024-01-15');
